Derive copy (#31)
* Derive Copy for Multihash and RawMultihash

Seems to work without any further modifications

* Use u8::max_value() instead of u8::MAX

had to do this to get it to compile with +nightly, otherwise I get

error[E0599]: no associated item named `MAX` found for type `u8` in the current scope
  --> src/hasher.rs:80:45
   |
80 |         if size > S::to_u64() || size > u8::MAX as u64 {
   |                                             ^^^ associated item not found in `u8`